-- USE MASTER
-- GO
--
CREATE DATABASE IF NOT EXISTS btck_shopqa;
USE btck_shopqa;
-- --
-- TẠO BẢNG PHANLOAI
CREATE TABLE IF NOT EXISTS PHANLOAI
(
MALOAI CHAR(10) PRIMARY KEY,
TENLOAI VARCHAR(50)
);

-- TẠO BẢNG HANGHOA
CREATE TABLE IF NOT EXISTS HANGHOA
(
MAHH CHAR(10) PRIMARY KEY,
TENHH VARCHAR(50),
GIABAN DECIMAL (10,2),
SL_HIENCO INT,
MALOAI CHAR(10)
-- foreign key MALOAI references PHANLOAI(MALOAI)
);

-- TẠO BẢNG NHACUNGCAP
CREATE TABLE IF NOT EXISTS NHACUNGCAP
(
MANCC INT AUTO_INCREMENT PRIMARY KEY,
TENNCC VARCHAR(100),
DIACHI VARCHAR(100),
DIENTHOAI CHAR(15)
);

-- TẠO BẢNG HOADON_NCC
CREATE TABLE IF NOT EXISTS HOADON_NCC
(
MAHD INT AUTO_INCREMENT PRIMARY KEY,
NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
TONGTIEN DECIMAL (10,2),
TINHTRANGTT CHAR(10),
MANCC INT,
MANV CHAR(10),
);

-- TẠO BẢNG HOADONMUA = CHI TIẾT BẢNG HÓA ĐƠN NCC + HÀNG HÓA
CREATE TABLE IF NOT EXISTS HOADONMUA
(
MAHD INT ,
MAHH CHAR(10),
N_DENHAN DATETIME,
SOLUONG INT,
DONGIA DECIMAL (10,2),
HINHTHUCTT CHAR(20),
PRIMARY KEY (MAHD,MAHH)
);

-- TẠO BẢNG KHACHHANG
CREATE TABLE IF NOT EXISTS KHACHHANG
(
MAKH INT AUTO_INCREMENT PRIMARY KEY,
TENKH VARCHAR(50),
DIACHI VARCHAR(100),
EMAIL VARCHAR (100) UNIQUE,
PASSWORDKH VARCHAR(255),
DIENTHOAI CHAR(15) UNIQUE,
N_TAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
N_CAPNHAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
EMAIL_AT DATETIME null,

);

-- TẠO BẢNG HOADON_KH
CREATE TABLE IF NOT EXISTS HOADON_KH
(
MAHD INT AUTO_INCREMENT PRIMARY KEY,
N_TAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
TONGTIEN DECIMAL (10,2),
TINHTRANG CHAR(10),
MAKH INT,
MANV CHAR(10)
);

-- TẠO BẢNG HOADONBAN
CREATE TABLE IF NOT EXISTS HOADONBAN
(
MAHD INT,
MAHH CHAR(10),
N_DENHAN DATETIME,
SOLUONG INT,
DONGIA DECIMAL (10,2),
HINHTHUCTT CHAR(20),
PRIMARY KEY (MAHD,MAHH)
);

-- TẠO BẢNG DANHGIA_SP
CREATE TABLE IF NOT EXISTS DANHGIA_SP
(
MAKH INT,
MAHH CHAR(10),
DIEM_DG INT,
NGAY_DG TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
NOIDUNG VARCHAR(255),
PRIMARY KEY (MAKH,MAHH)
);

-- TẠO BẢNG NHANVIEN
CREATE TABLE IF NOT EXISTS NHANVIEN
(
MANV CHAR(10) PRIMARY KEY,
TENNV VARCHAR(50),
MAQL CHAR(10),
DIACHI VARCHAR(100),
MALUONG CHAR(10)
);
-- TẠO BẢNG BANGLUONG
CREATE TABLE IF NOT EXISTS BANGLUONG
(
MALUONG CHAR(10) PRIMARY KEY,
MUCLUONG DECIMAL (10,2)
);
-- TẠO BẢNG GIỎ HÀNG
CREATE TABLE IF NOT EXISTS GIOHANG
(
MAGIO INT AUTO_INCREMENT PRIMARY KEY,
N_TAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
N_CAPNHAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
MAKH INT 
);

-- -----------------------------------

-- -----------------------------------

-- TẠO LIÊN KẾT:
ALTER TABLE HANGHOA
ADD CONSTRAINT FK_HANGHOA_PHANLOAI
FOREIGN KEY (MALOAI)
REFERENCES PHANLOAI(MALOAI);



-- FOREIGN KEY (user_id) REFERENCES users(id)
--
ALTER TABLE HOADON_NCC
ADD CONSTRAINT FK_HOADON_NCC_NHACUNGCAP
FOREIGN KEY (MANCC)
REFERENCES NHACUNGCAP (MANCC)
GO
--
ALTER TABLE BAOGIA_NCC
ADD CONSTRAINT FK_BAOGIA_NCC_NHACUNGCAP
FOREIGN KEY (MANCC)
REFERENCES NHACUNGCAP (MANCC)
GO
ALTER TABLE BAOGIA_NCC
ADD CONSTRAINT FK_BAOGIA_NCC_HANGHOA
FOREIGN KEY (MAHH)
REFERENCES HANGHOA (MAHH)
GO
--
ALTER TABLE CUNGCAP_NCC
ADD CONSTRAINT FK_CUNGCAP_NCC_NHACUNGCAP
FOREIGN KEY (MANCC)
REFERENCES NHACUNGCAP (MANCC)
GO
ALTER TABLE CUNGCAP_NCC
ADD CONSTRAINT FK_CUNGCAP_NCC_HANGHOA
FOREIGN KEY (MAHH)
REFERENCES HANGHOA (MAHH)
GO
--
ALTER TABLE HOADONMUA
ADD CONSTRAINT FK_HOADONMUA_HOADON_NCC
FOREIGN KEY (MAHD)
REFERENCES HOADON_NCC (MAHD)
GO
ALTER TABLE HOADONMUA
ADD CONSTRAINT FK_HOADONMUA_HANGHOA
FOREIGN KEY (MAHH)
REFERENCES HANGHOA (MAHH)
GO
--LIENQUANKHACHHANG
ALTER TABLE HOADON_KH
ADD CONSTRAINT FK_HOADON_KH_KHACHHANG
FOREIGN KEY (MAKH)
REFERENCES KHACHHANG (MAKH)
GO
--
--
ALTER TABLE BAOGIA_KH
ADD CONSTRAINT FK_BAOGIA_KH_KHACHHANG
FOREIGN KEY (MAKH)
REFERENCES KHACHHANG (MAKH)
GO
ALTER TABLE BAOGIA_KH
ADD CONSTRAINT FK_BAOGIA_KH_HANGHOA
FOREIGN KEY (MAHH)
REFERENCES HANGHOA (MAHH)
GO
--
--
ALTER TABLE CUNGCAP_KH
ADD CONSTRAINT FK_CUNGCAP_KH_KHACHHANG
FOREIGN KEY (MAKH)
REFERENCES KHACHHANG (MAKH)
GO
ALTER TABLE CUNGCAP_KH
ADD CONSTRAINT FK_CUNGCAP_KH_HANGHOA
FOREIGN KEY (MAHH)
REFERENCES HANGHOA (MAHH)
GO
--
--
ALTER TABLE HOADONBAN
ADD CONSTRAINT FK_HOADONBAN_HOADON_KH
FOREIGN KEY (MAHD)
REFERENCES HOADON_KH (MAHD)
GO
ALTER TABLE HOADONBAN
ADD CONSTRAINT FK_HOADONBAN_HANGHOA
FOREIGN KEY (MAHH)
REFERENCES HANGHOA (MAHH)
GO